### ISSUE TITLE
Problem with validations declared in active_admin_translates

### ISSUE THREAD

**Issue by Archimidis** [unmantained-activeadmin-plugins/activeadmin-globalize#25]
Hello! I have the following model that currently is managed through active admin:

``` ruby
class Item < ActiveRecord::Base
  validates :title, presence: true
  validates :short_description, presence: true

  translates :title, :short_description, fallbacks_for_empty_translations: true

  active_admin_translates :title, :short_description do
    validates :title, presence: true
    validates :short_description, presence: true
end
```

Recently I had the need to create some items through the seed file and I had the following problem with validations inside declared active_admin_translates.

What I do:
1. I instantiate a new Item object and I assign both _title_ and _short_description_ for the locales I want.
2. I call _valid?_ and it returns true. I can see both _title_ and _short_description_ for all my locales.
3. I call _save_ but fails because of the validations declared in the active_admin_translates block. As in step 2, if I call _title_ and _short_description_ for all my locales I see the values I assigned on step 1.

What's going on here? Am I doing something wrong? Also, do I need the 2 validations outside the active_admin_translates block?

I really appreciate any help you can provide.

**Comment by dtengeri** [comment]
I've faced with the same problem. The solution was that I had to set the translated fields in the translations itself.
You can get the translations by 

``` ruby
item.translations
```

First you have to build the translation objects for each locale and set the value of the translated fields in these objects.
For example: 

``` ruby
item = Item.new
translation = item.translations.build :locale => :en
translation.title = '....'
translation.short_description = '....'
```

**Comment by Archimidis** [comment]
The above method was indeed the solution. Thank you very much!
