### ISSUE TITLE
Version for Rails 3

### ISSUE THREAD

**Issue by codingluke** [unmantained-activeadmin-plugins/activeadmin-globalize#29]
Hi @stefanoverna 
I use you gem for an app which works with Rails3. As ActiveAdmin is not jet really stable on rails 4 and also other gems we are useing, I dont want to upgrade to Rails4 jet.
Now the globalize gem changed the name and also you already updated it. That's good. The only problem now is, that you have as the dependency globalize version 4:

``` ruby
# activeadmin-globalize.gemspec
s.add_dependency "globalize", '~> 4.0.0'
```

using Rails 3 it is recommended to use globalize version 3.1.0

``` ruby
gem 'globalize', '~> 3.1.0'
```

It would be great, if you could tag a version which uses Version 3. The features should be the same (https://github.com/globalize/globalize#installation). Otherwise I have to fork the gem and change it manually.
THX!

**Comment by tiredenzo** [comment]
gem 'activeadmin-globalize3'
still works here :)

but i wish this new version could manage both versions of rails if possible ^_^

**Comment by JonAbrams** [comment]
@tiredenzo Note though that activeadmin-globalize3 depends on the gem 'globalize3' not 'globalize' which is now recommended (even for Rails 3).

For now I guess I'll just have to use 'globalize3' if I want to make use of active-adminglobalize with Rails 3.x
